[package]
name = "hogan"
version = "0.2.3"
authors = ["Jonathan Morley <jmorley@cvent.com>"]

[[bin]]
name = "hogan"
path = "src/main.rs"
doc = false

[dependencies]
failure = "0.1.1"
git2 = "0.7.1"
handlebars = "0.32.0"
itertools = "0.7.3"
json-patch = "0.2.0"
log = "0.4"
quicli = "0.2"
regex = "0.2"
rouille = "2.1"
serde = "1.0"
serde_derive = "1.0"
serde_json = "1.0"
shellexpand = "1.0"
structopt = "0.2.5"
tempfile = "3.0"
url = "1.7"
walkdir = "2.0"
zip = "0.3.2"
